name: Python build

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.2'

    - name: Setup SWIG
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y swig

    - name: Setup Mingw
      shell: bash
      run: sudo apt-get install -y swig mingw-w64

    - name: Setup GCC
      shell: bash
      run: sudo apt-get install -y swig mingw-w64 gcc g++

    - name: Setup python build
      shell: bash
      run: python -m pip install build

    - name: Generate
      shell: bash
      run: ./gradlew mingwX64Binaries

    - name: Adjust header
      shell: bash
      run: |
        sed -i \
          -e 's/_\$$/_/g' \
          -e 's/\$//g' \
          "doordeck-sdk/build/bin/mingwX64/releaseShared/Doordeck.Headless.Sdk_api.h"

    - name: Generate pyproject file
      shell: bash
      run: ./gradlew -Pversion=1.0.0 pythonPack

    - name: Download python for windows
      shell: bash
      run: |
        curl -LO https://www.python.org/ftp/python/3.13.2/python-3.13.2-embed-amd64.zip
        mv python-3.13.2-embed-amd64.zip doordeck-sdk/build/bin/mingwX64/python
        unzip doordeck-sdk/build/bin/mingwX64/python/python-3.13.2-embed-amd64.zip -d doordeck-sdk/build/bin/mingwX64/python/windows-python

    - name: Generate bindings
      shell: bash
      run: |
        swig -python -py3 -D_MSC_VER -o doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk_wrap.c \
          -outdir doordeck-sdk/build/bin/mingwX64/python/src/doordeck_headless_sdk \
          doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk.i

    - name: Compile bindings
      shell: bash
      run: |
        x86_64-w64-mingw32-gcc -shared -o doordeck-sdk/build/bin/mingwX64/python/src/doordeck_headless_sdk/_doordeck_headless_sdk.pyd \
          doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk_wrap.c \
          doordeck-sdk/build/bin/mingwX64/releaseShared/Doordeck.Headless.Sdk.dll \
          -I $(python -c "import sysconfig; print(sysconfig.get_paths()['include'])") \
          -L doordeck-sdk/build/bin/mingwX64/python/windows-python \
          -lpython313