name: Python bindings generation

inputs:
  USE_LAST_TAG:
    description: Determines whether the last tag should be used in the pythonPack Gradle task
    required: true

env:
  PYTHON_VERSION: '3.13.2'

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup SWIG
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y swig

    - name: Setup Mingw
      shell: bash
      run: sudo apt-get install -y swig mingw-w64

    - name: Setup GCC
      shell: bash
      run: sudo apt-get install -y swig mingw-w64 gcc g++

    - name: Setup python build
      shell: bash
      run: python -m pip install build

    - name: Generate
      shell: bash
      run: ./gradlew mingwX64Binaries

    - name: Adjust header
      shell: bash
      run: |
        sed -i \
          -e 's/_\$$/_/g' \
          -e 's/\$//g' \
          "doordeck-sdk/build/bin/mingwX64/releaseShared/Doordeck.Headless.Sdk_api.h"

    - name: Generate pyproject file
      shell: bash
      run: |
        if [ "${{ inputs.USE_LAST_TAG }}" = "true" ]; then
          ./gradlew -Prelease.useLastTag=true pythonPack
        else
          ./gradlew pythonPack
        fi

    - name: Download python for windows
      shell: bash
      run: |
        curl -LO https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/python-${{ env.PYTHON_VERSION }}-embed-amd64.zip
        mv python-${{ env.PYTHON_VERSION }}-embed-amd64.zip doordeck-sdk/build/bin/mingwX64/python
        unzip doordeck-sdk/build/bin/mingwX64/python/python-${{ env.PYTHON_VERSION }}-embed-amd64.zip -d doordeck-sdk/build/bin/mingwX64/python/windows-python

    - name: Generate bindings
      shell: bash
      run: |
        swig -python -D_MSC_VER -o doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk_wrap.c \
          -outdir doordeck-sdk/build/bin/mingwX64/python/src/doordeck_headless_sdk \
          doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk.i

    - name: Compile bindings
      shell: bash
      run: |
        x86_64-w64-mingw32-gcc -shared -o doordeck-sdk/build/bin/mingwX64/python/src/doordeck_headless_sdk/_doordeck_headless_sdk.pyd \
          doordeck-sdk/build/bin/mingwX64/python/doordeck_headless_sdk_wrap.c \
          doordeck-sdk/build/bin/mingwX64/releaseShared/Doordeck.Headless.Sdk.dll \
          -I $(python -c "import sysconfig; print(sysconfig.get_paths()['include'])") \
          -L doordeck-sdk/build/bin/mingwX64/python/windows-python \
          -lpython313